/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface CreateUserExerciseRequestDto {
    userId: number;
    exerciseApiId: string;
    exerciseName: string;
    time?: TimeOnly;
}

export interface ExerciseByIdData {
    exerciseId: string;
    name: string;
    imageUrl?: string | null;
    bodyParts?: Array<string>;
    equipments?: Array<string>;
    exerciseTips?: Array<string>;
    exerciseType?: string | null;
    instructions?: Array<string>;
    keywords?: Array<string>;
    overview?: string | null;
    secondaryMuscles?: Array<string>;
    targetMuscles?: Array<string>;
    variations?: Array<string>;
    relatedExerciseIds?: Array<string>;
    videoUrl?: string | null;
}

export interface ExerciseByIdResponseDto {
    success?: boolean;
    data?: ExerciseByIdData;
}

export interface ExerciseDto {
    apiId?: string | null;
    name?: string | null;
    time?: TimeOnly;
}

export interface ExerciseFilterData {
    exerciseId: string;
    name: string;
    imageUrl?: string | null;
    bodyParts?: Array<string>;
    equipments?: Array<string>;
    exerciseType?: string | null;
    keywords?: Array<string>;
    secondaryMuscles?: Array<string>;
    targetMuscles?: Array<string>;
}

export interface ExerciseFilterRequestDto {
    name?: string | null;
    keywords?: string | null;
    targetMuscles?: string | null;
    secondaryMuscles?: string | null;
    exerciseType?: string | null;
    bodyParts?: string | null;
    equipments?: string | null;
    limit?: string | null;
    after?: string | null;
    before?: string | null;
}

export interface ExerciseFilterResponseDto {
    success?: boolean;
    data?: Array<ExerciseFilterData>;
    meta?: Metadata;
}

export interface ExerciseSearchData {
    exerciseId: string;
    name: string;
    imageUrl?: string | null;
}

export interface ExerciseSearchRequestDto {
    search?: string | null;
}

export interface ExerciseSearchResponseDto {
    success?: boolean;
    data?: Array<ExerciseSearchData>;
}

export interface Metadata {
    total?: number;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;
    nextCursor?: string | null;
    previousCursor?: string | null;
}

export interface TimeOnly {
    hour?: number;
    minute?: number;
    readonly second?: number;
    readonly millisecond?: number;
    readonly microsecond?: number;
    readonly nanosecond?: number;
    readonly ticks?: number;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
