/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Exercise controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ExerciseByIdResponseDto, ExerciseSearchRequestDto, ExerciseSearchResponseDto, ExerciseFilterRequestDto, ExerciseFilterResponseDto } from "../models";

@Injectable({ providedIn: "root" })
export class ExerciseService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiV1ExerciseIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ExerciseByIdResponseDto>;
    apiV1ExerciseIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ExerciseByIdResponseDto>>;
    apiV1ExerciseIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ExerciseByIdResponseDto>>;
    apiV1ExerciseIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/exercise/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1ExerciseSearchPost(exerciseSearchRequestDto?: ExerciseSearchRequestDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<ExerciseSearchResponseDto>;
    apiV1ExerciseSearchPost(exerciseSearchRequestDto?: ExerciseSearchRequestDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ExerciseSearchResponseDto>>;
    apiV1ExerciseSearchPost(exerciseSearchRequestDto?: ExerciseSearchRequestDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ExerciseSearchResponseDto>>;
    apiV1ExerciseSearchPost(exerciseSearchRequestDto?: ExerciseSearchRequestDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/exercise/search`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, exerciseSearchRequestDto, requestOptions);
    }

    apiV1ExerciseFilterPost(exerciseFilterRequestDto?: ExerciseFilterRequestDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<ExerciseFilterResponseDto>;
    apiV1ExerciseFilterPost(exerciseFilterRequestDto?: ExerciseFilterRequestDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ExerciseFilterResponseDto>>;
    apiV1ExerciseFilterPost(exerciseFilterRequestDto?: ExerciseFilterRequestDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ExerciseFilterResponseDto>>;
    apiV1ExerciseFilterPost(exerciseFilterRequestDto?: ExerciseFilterRequestDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/exercise/filter`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, exerciseFilterRequestDto, requestOptions);
    }
}
