/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { ExerciseService } from "./exercise.service";
export { UserExerciseService } from "./userExercise.service";
